---
# link tham khảo thêm https://serverfault.com/questions/783735/ansible-multiple-statements-with-the-same-variabless
#Example 1
- name: install NGINX
  host: all
  task: 
  - name: Install NGIN on Dedian
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian" and
          ansible_distribution_version == "16.04"
  - name: Install NGIN on Redhat
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat" or
          ansible_os_family == "SUSE"
# ansible_os_family, ansible_distribution_version là biến mà ansible xây dựng sẵn

#Example 2
- name: Install Softwares
  hosts: all
  vars:
    packages:
      - name: nginx
        required: True
      - name: mysql
        required: True
      - name: apache
        required: False
  task:
  - name: Install "{{ item.name }}" on Debian
    apt:
      name: "{{ item.name }}"
      state: present
    loop: "{{ packages }}"

# Example3
- name: check status
  hosts: localhost
  tasks:
    - command: service http status
      register: result
    - mail:
      ....
      when: result.stdout.find('down') != -1

# Example4
- name: using items-list
- vars:
    userlist:
      - user_name: user1
        user_description: user 1
        user_id: 2000
      - user_name: user2
        user_description: user 2
        user_id: 2001
  block:
    - name: Create real users
      user: name="{{item.user_name}}" comment="{{item.user_description}}" home="/home/{{item.user_name}}" shell="/bin/bash" uid="{{item.user_id}}"
      with_items: "{{ userlist }}"

    - name: Copy SSH keys
      copy:
        src: "keys/{{ item.user_name }}.key"
        dest: "/home/{{ item.user_name }}/.ssh/authorized_keys"
        owner: "{{ item.user_name }}"
        group: "{{ item.user_name }}"
        mode: 0600
      with_items: "{{ userlist }}"